// packages/react/src/useAIStream.ts
import { useState, useEffect, useCallback, useRef } from 'react'
import { AIStream } from '@ainative/ai-kit-core'
import type { Message, Usage, StreamConfig } from '@ainative/ai-kit-core'

export interface UseAIStreamResult {
  messages: Message[]
  isStreaming: boolean
  error: Error | null
  send: (content: string) => Promise<void>
  reset: () => void
  retry: () => Promise<void>
  stop: () => void
  usage: Usage
}

/**
 * React hook for AI streaming
 * Manages messages state and streaming lifecycle automatically
 */
export function useAIStream(config: StreamConfig): UseAIStreamResult {
  const [messages, setMessages] = useState<Message[]>([])
  const [isStreaming, setIsStreaming] = useState(false)
  const [error, setError] = useState<Error | null>(null)
  const [usage, setUsage] = useState<Usage>({
    promptTokens: 0,
    completionTokens: 0,
    totalTokens: 0,
  })

  const streamRef = useRef<AIStream | null>(null)

  // Initialize stream
  useEffect(() => {
    const stream = new AIStream(config)

    // Listen to events
    stream.on('message', (message: Message) => {
      setMessages((prev) => {
        const existing = prev.find((m) => m.id === message.id)
        if (existing) {
          return prev.map((m) => (m.id === message.id ? message : m))
        }
        return [...prev, message]
      })
    })

    stream.on('streaming-start', () => {
      setIsStreaming(true)
      setError(null)
    })

    stream.on('streaming-end', () => {
      setIsStreaming(false)
    })

    stream.on('error', (err: Error) => {
      setError(err)
      setIsStreaming(false)
    })

    stream.on('usage', (newUsage: Usage) => {
      setUsage(newUsage)
    })

    stream.on('reset', () => {
      setMessages([])
      setError(null)
      setUsage({
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
      })
    })

    streamRef.current = stream

    return () => {
      stream.removeAllListeners()
      stream.stop()
    }
  }, []) // Empty deps - only initialize once

  const send = useCallback(async (content: string) => {
    if (!streamRef.current) return
    try {
      await streamRef.current.send(content)
    } catch (err) {
      setError(err as Error)
    }
  }, [])

  const reset = useCallback(() => {
    if (!streamRef.current) return
    streamRef.current.reset()
  }, [])

  const retry = useCallback(async () => {
    if (!streamRef.current) return
    try {
      await streamRef.current.retry()
    } catch (err) {
      setError(err as Error)
    }
  }, [])

  const stop = useCallback(() => {
    if (!streamRef.current) return
    streamRef.current.stop()
  }, [])

  return {
    messages,
    isStreaming,
    error,
    send,
    reset,
    retry,
    stop,
    usage,
  }
}

// packages/react/src/useAIStream.vue.ts
import { ref, onMounted, onUnmounted, Ref } from 'vue'
import { AIStream } from '@ainative/ai-kit-core'
import type { Message, Usage, StreamConfig } from '@ainative/ai-kit-core'

export interface UseAIStreamResult {
  messages: Ref<Message[]>
  isStreaming: Ref<boolean>
  error: Ref<Error | null>
  send: (content: string) => Promise<void>
  reset: () => void
  retry: () => Promise<void>
  stop: () => void
  usage: Ref<Usage>
}

/**
 * Vue 3 composable for AI streaming
 * Manages messages state and streaming lifecycle automatically using Composition API
 */
export function useAIStream(config: StreamConfig): UseAIStreamResult {
  const messages = ref<Message[]>([])
  const isStreaming = ref(false)
  const error = ref<Error | null>(null)
  const usage = ref<Usage>({
    promptTokens: 0,
    completionTokens: 0,
    totalTokens: 0,
  })

  let stream: AIStream | null = null

  // Initialize stream
  onMounted(() => {
    stream = new AIStream(config)

    // Listen to events
    stream.on('message', (message: Message) => {
      const existing = messages.value.find((m) => m.id === message.id)
      if (existing) {
        messages.value = messages.value.map((m) =>
          m.id === message.id ? message : m
        )
      } else {
        messages.value = [...messages.value, message]
      }
    })

    stream.on('streaming-start', () => {
      isStreaming.value = true
      error.value = null
    })

    stream.on('streaming-end', () => {
      isStreaming.value = false
    })

    stream.on('error', (err: Error) => {
      error.value = err
      isStreaming.value = false
    })

    stream.on('usage', (newUsage: Usage) => {
      usage.value = newUsage
    })

    stream.on('reset', () => {
      messages.value = []
      error.value = null
      usage.value = {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
      }
    })
  })

  // Cleanup on unmount
  onUnmounted(() => {
    if (stream) {
      stream.removeAllListeners()
      stream.stop()
      stream = null
    }
  })

  const send = async (content: string): Promise<void> => {
    if (!stream) return
    try {
      await stream.send(content)
    } catch (err) {
      error.value = err as Error
    }
  }

  const reset = (): void => {
    if (!stream) return
    stream.reset()
  }

  const retry = async (): Promise<void> => {
    if (!stream) return
    try {
      await stream.retry()
    } catch (err) {
      error.value = err as Error
    }
  }

  const stop = (): void => {
    if (!stream) return
    stream.stop()
  }

  return {
    messages,
    isStreaming,
    error,
    send,
    reset,
    retry,
    stop,
    usage,
  }
}
